version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:443"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: bpg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "bpg", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_startup:/var/lib/postgresql/data  

volumes:
  postgres_startup: