using System.ComponentModel;
using Application.Spyfall.Models;

namespace Application.Spyfall;

/// <summary>
/// A request to get a card in a spyfall game.
/// </summary>
public record GetCardRequest
{
    /// <summary>
    /// A game key generated by POST /game
    /// </summary>
    public required string Key { get; init; }
    /// <summary>
    /// A 1-based player number.
    /// </summary>
    public byte Number { get; init; } = 1;
}

public class GetCardHandler : IRequestHandler<GetCardRequest, PlayerCard>
{
    public Task<PlayerCard> HandleAsync(GetCardRequest request, CancellationToken ct = default)
    {
        var game = Game.FromKey(request.Key);
        var card = game.GetCard((byte)(request.Number - 1));
        return Task.FromResult(card);
    }
}